# Ruff configuration for Secrets Password Manager

# Target Python version
target-version = "py311"

# Line length (consistent with Black)
line-length = 88

# Enable specific rule categories
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "ARG",  # flake8-unused-arguments
    "SIM",  # flake8-simplify
    "RET",  # flake8-return
    "PLR",  # Pylint refactor
    "PLW",  # Pylint warning
    "PLE",  # Pylint error
    "S",    # flake8-bandit (security)
    "N",    # pep8-naming
    "ANN",  # flake8-annotations
]

# Ignore specific rules
ignore = [
    "E501",   # Line too long (handled by black)
    "B008",   # Do not perform function calls in argument defaults
    "S101",   # Use of assert detected (allow in tests)
    "ANN101", # Missing type annotation for self
    "ANN102", # Missing type annotation for cls
    "ANN204", # Missing return type annotation for special method
    "ARG002", # Unused method argument (common in event handlers)
    "PLR0913", # Too many arguments to function call
    "PLR2004", # Magic value used in comparison
]

# Per-file ignores
[per-file-ignores]
"tests/*" = [
    "S101",   # Allow assert in tests
    "ANN",    # Don't require annotations in tests
    "ARG",    # Allow unused arguments in test fixtures
    "PLR2004", # Allow magic values in tests
]
"setup_wizard/*" = [
    "ARG002", # UI callbacks often have unused arguments
]
"src/secrets/ui/*" = [
    "ARG002", # UI callbacks often have unused arguments
]

# Exclude directories
exclude = [
    ".git",
    ".venv",
    "venv",
    "build",
    "dist",
    "*.egg-info",
    "__pycache__",
    ".pytest_cache",
    ".coverage",
]

# Import sorting
[isort]
known-first-party = ["secrets"]
force-single-line = true
split-on-trailing-comma = true